//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Old
    {
        public System.Guid UserId { get; set; }
        public string USER_NAME { get; set; }
        public string USER_SURNAME { get; set; }
        public string PERSAL { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string EMAIL { get; set; }
        public string CONTACT_NO { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string MAINT_USER { get; set; }
        public Nullable<System.DateTime> MAINT_DATE { get; set; }
    }
}
